name: CI - Build & Dockerize

on:
  push:
    branches: [ "ci-docker-images" ]
  pull_request:
    branches: [ "ci-docker-images" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # IMPORTANT for pushing images

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ---------- LOGIN TO GHCR ----------
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ---------- BACKEND IMAGE ----------
    - name: Build & Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./ChatVideoClient/chat-video-client
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/myapp-backend:latest

    # ---------- FRONTEND IMAGE ----------
    - name: Build & Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/myapp-frontend:latest
